name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
  workflow_dispatch:       

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.2

    - name: Verify go.sum exists
      working-directory: ./backend
      run: ls -l go.sum

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: ./backend
      run: |
        sudo rm -rf $(go env GOPATH)/pkg/mod
        go mod tidy
        go mod download

    - name: Generate Ent code
      working-directory: ./backend
      run: go generate ./ent

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install golangci-lint
      working-directory: ./backend
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
      env:
        GO111MODULE: "on"

    - name: Run Go Linter
      working-directory: ./backend
      run: |
        go mod tidy
        go mod download
        golangci-lint run

    - name: Run Backend Tests
      working-directory: ./backend
      run: go test ./...

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run Frontend Linter
      working-directory: ./frontend
      run: npx eslint src/

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test

    - name: Start Docker Compose
      working-directory: ./backend
      run: |
        docker compose --env-file backend/.env.development up -d 
      env:
        DOCKER_BUILDKIT: 1
